# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/master/json-schema/config-schema.json
#####################################################
#                 HOLIDAYS 9.0                      #
#####################################################

templates:
  Holiday:
    sort_title: "!!<<collection_name>>"
    smart_label: random
    sync_mode: sync
    visible_home: false

# Holiday collections that will show up when the holiday has started and disappear when it has ended
collections:
  SÃ©lection NoÃ«l ğŸ…:
    template: { name: Holiday }
    visible_home: range(12/01-12/26)
    visible_library: range(12/01-12/26)
    visible_shared: range(12/01-12/26)
    summary: Ho ho ho.
    file_poster: config/posters/Christmas.png
    letterboxd_list:
      - https://letterboxd.com/patrickb15/list/christmas/
      - https://letterboxd.com/ryukiation/list/christmas/

  SÃ©lection PÃ¢ques ğŸ£:
    template: { name: Holiday }
    visible_home: range(03/22-04/20)
    visible_library: range(03/22-04/20)
    visible_shared: range(03/22-04/20)
    summary: The Easter bunny is here!
    file_poster: config/posters/Easter.png
    letterboxd_list:
      - https://letterboxd.com/patrickb15/list/easter/
      - https://letterboxd.com/shyann_thomas/list/easter/
      - https://letterboxd.com/gabyanahisoto/list/easter/

  SÃ©lection FÃªte des PÃ¨res ğŸ‘¨â€ğŸ‘¦:
    template: { name: Holiday }
    visible_home: range(06/08-06/21)
    visible_library: range(06/08-06/21)
    visible_shared: range(06/08-06/21)
    summary: Every Fathers Special day.
    file_poster: config/posters/Fathers Day.png
    letterboxd_list:
      - https://letterboxd.com/patrickb15/list/fathers-day/
      - https://letterboxd.com/joshhiso/list/fathers-day/

  SÃ©lection Halloween ğŸ‘»:
    template: { name: Holiday }
    visible_home: range(10/01-10/31)
    visible_library: range(10/01-10/31)
    visible_shared: range(10/01-10/31)
    summary: This is Halloween!
    file_poster: config/posters/Halloween..png
    letterboxd_list:
      - https://letterboxd.com/summerof83/list/halloween/
      - https://letterboxd.com/jennomaes/list/halloween/
      - https://letterboxd.com/patrickb15/list/halloween/

  SÃ©lection FÃªte des MÃ¨res ğŸ‘©â€ğŸ‘§:
    template: { name: Holiday }
    visible_home: range(05/25-06/07)
    visible_library: range(05/25-06/07)
    visible_shared: range(05/25-06/07)
    summary: Every Mothers special day.
    file_poster: config/posters/Mothers Day.png
    letterboxd_list:
      - https://letterboxd.com/patrickb15/list/mothers-day/
      - https://letterboxd.com/gainsbourg/list/mothers-day/

  SÃ©lection Nouvel An ğŸ¾:
    template: { name: Holiday }
    visible_home: range(12/30-01/05)
    visible_library: range(12/30-01/05)
    visible_shared: range(12/30-01/05)
    summary: Happy New Year!
    file_poster: config/posters/New Year.png
    letterboxd_list:
      - https://letterboxd.com/marilynette/list/new-years-movies/
      - https://letterboxd.com/dialmformelissa/list/new-years-movies/
      - https://letterboxd.com/mikeymorgz/list/new-years-movies/

  SÃ©lection Saint Valentin ğŸ’˜:
    template: { name: Holiday }
    visible_home: range(02/14-02/15)
    visible_library: range(02/14-02/15)
    visible_shared: range(02/14-02/15)
    summary: Love me tender, love me sweet.
    file_poster: config/posters/Valentines Day.png
    letterboxd_list:
      - https://letterboxd.com/yktv/list/valentines-day/
      - https://letterboxd.com/riotglasses/list/valentines-day/
      - https://letterboxd.com/plutosummer/list/valentines-day/
