# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/master/json-schema/config-schema.json
#####################################################
#                 HOLIDAYS 8.0                      #
#####################################################

templates:
  Holiday:
    sort_title: "!!_<<collection_name>>"
    smart_label: random
    sync_mode: sync
    visible_home: false

# Holiday collections that will show up when the holiday has started and disappear when it has ended
collections:
  SÃ©lection NoÃ«l ğŸ…:
    template: { name: Holiday }
    visible_home: range(12/01-12/26)
    visible_library: range(12/01-12/26)
    visible_shared: range(12/01-12/26)
    summary: Ho ho ho.
    file_poster: config/posters/Christmas.png
    trakt_list:
      - https://trakt.tv/users/ad76/lists/hallmark-christmas?sort=released,asc
      - https://trakt.tv/users/k0meta/lists/christmas-extravaganza-non-tv-movie
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/questdvd/lists/absolute-hayes-christmas-classics
      - https://trakt.tv/users/littlestella3/lists/christmas

  SÃ©lection PÃ¢ques ğŸ£:
    template: { name: Holiday }
    visible_home: range(03/22-04/20)
    visible_library: range(03/22-04/20)
    visible_shared: range(03/22-04/20)
    summary: The Easter bunny is here!
    file_poster: config/posters/Easter.png
    trakt_list:
      - https://trakt.tv/users/smwixted/lists/easter?sort=votes,asc
      - https://trakt.tv/users/tarzanislav/lists/easter?sort=added,asc

  SÃ©lection FÃªte des PÃ¨res ğŸ‘¨â€ğŸ‘¦:
    template: { name: Holiday }
    visible_home: range(06/08-06/21)
    visible_library: range(06/08-06/21)
    visible_shared: range(06/08-06/21)
    summary: Every Fathers Special day.
    file_poster: config/posters/Fathers Day.png
    trakt_list:
      - https://trakt.tv/users/fcisco13/lists/dad-movies?sort=rank,asc
      - https://trakt.tv/users/segfaulted/lists/movies-for-dad?sort=rank,asc

  SÃ©lection Halloween ğŸ‘»:
    template: { name: Holiday }
    visible_home: range(10/01-10/31)
    visible_library: range(10/01-10/31)
    visible_shared: range(10/01-10/31)
    summary: This is Halloween!
    file_poster: config/posters/Halloween..png
    trakt_list:
      - https://trakt.tv/users/29zombies/lists/halloween
      - https://trakt.tv/users/membball84/lists/halloween-halloween-halloween?sort=title,asc
      - https://trakt.tv/users/kairbear08/lists/halloween
      - https://trakt.tv/users/mybicycle/lists/halloween

  SÃ©lection FÃªte des MÃ¨res ğŸ‘©â€ğŸ‘§:
    template: { name: Holiday }
    visible_home: range(05/25-06/07)
    visible_library: range(05/25-06/07)
    visible_shared: range(05/25-06/07)
    summary: Every Mothers special day.
    file_poster: config/posters/Mothers Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/mother-s-day?sort=rank,asc
      - https://trakt.tv/users/mdm144/lists/mother-s-day?sort=rank,asc

  SÃ©lection Nouvel An ğŸ¾:
    template: { name: Holiday }
    visible_home: range(12/30-01/05)
    visible_library: range(12/30-01/05)
    visible_shared: range(12/30-01/05)
    summary: Happy New Year!
    file_poster: config/posters/New Year.png
    trakt_list:
      - https://trakt.tv/users/gullibletransport/lists/new-year?sort=random,asc
      - https://trakt.tv/users/sympli/lists/new-years-movies?sort=rank,asc
      - https://trakt.tv/users/padawan_seneca/lists/new-years-eve?sort=rank,asc
      - https://trakt.tv/users/galacticboy/lists/new-years?sort=rank,asc

  SÃ©lection Saint Valentin ğŸ’˜:
    template: { name: Holiday }
    visible_home: range(02/14-02/15)
    visible_library: range(02/14-02/15)
    visible_shared: range(02/14-02/15)
    summary: Love me tender, love me sweet.
    file_poster: config/posters/Valentines Day.png
    trakt_list:
      - https://trakt.tv/users/movie-pal/lists/valentine-s-day
      - https://trakt.tv/users/barsaky/lists/den-svateho-valentina-valentine-s-day
      - https://trakt.tv/users/abbelea/lists/movies-best-of-love
